org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
PLAY_STORE_SERVICE_ACCOUNT_JSON=playstore_svc_dummy.json
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
