name: sbb_maps_flutter
description: Incorporate SBB styled maps into your flutter application based on Maplibre.
repository: https://github.com/SchweizerischeBundesbahnen/journey-maps-client-flutter
issue_tracker: https://github.com/SchweizerischeBundesbahnen/journey-maps-client-flutter/issues
topics: [ map, maps, maplibre ]

# version is set by Release Please GH Action
version: 2.6.1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

platforms:
  android:
  ios:

flutter:
  assets:
    - lib/fonts/
  fonts:
    - family: SBBIconsSmall
      fonts:
        - asset: packages/sbb_maps_flutter/fonts/font-sbb-icons-small.ttf
    - family: SBBWeb
      fonts:
        - asset: packages/sbb_maps_flutter/fonts/SBBWeb-Bold.ttf
          weight: 700
        - asset: packages/sbb_maps_flutter/fonts/SBBWeb-Roman.ttf
          weight: 400
        - asset: packages/sbb_maps_flutter/fonts/SBBWeb-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/sbb_maps_flutter/fonts/SBBWeb-Light.ttf
          weight: 300
        - asset: packages/sbb_maps_flutter/fonts/SBBWeb-Thin.ttf
          weight: 200
        - asset: packages/sbb_maps_flutter/fonts/SBBWeb-Ultra-Light.ttf
          weight: 100

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/maplibre_gl
  maplibre_gl: ^0.22.0
  # https://pub.dev/packages/geolocator
  geolocator: ">=12.0.0 <14.0.0"
  # https://pub.dev/packages/logger
  logger: ^2.0.2+1
  # https://pub.dev/packages/collection
  collection: ^1.17.1

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/test
  test: ^1.24.0
  # https://pub.dev/packages/mockito
  mockito: ^5.4.2
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.7
