name: Publish to pub.dev

on:
  workflow_dispatch:

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter doctor -v
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs

      - run: flutter pub publish --force
